// Conteúdo do Playbook do Comercial, em dado tipado (a tela só desenha).
// Fonte: gp-operacoes, departamentos/comercial/ (playbook v1 de 26/09/2026, revisto em 03/10/2026, guia de
// produtos, playbooks e processos das três áreas), projetos/2026-09-estruturacao-do-comercial/concepcao.md,
// mentores/thiago-concer.md, marcas-e-publicos/ e mensageria/processos/disparar-por-api.md.
// Regra: as palavras são as do playbook (condensadas, nunca inventadas). O que está "a definir" lá, está aqui.
// Preço: só o vigente do arquivo do produto; valor de edição é histórico e não entra como preço.
// Texto aceita **negrito** (a tela desenha e a busca ignora os asteriscos).

/** Situação de um trecho que ainda não vale como regra. */
export type StatusTrecho = 'em_validacao' | 'a_definir' | 'a_validar' | 'a_revisar' | 'a_escrever';

export type Bloco =
  | { tipo: 'paragrafo'; texto: string }
  | { tipo: 'subtitulo'; texto: string }
  | { tipo: 'lista'; itens: string[]; numerada?: boolean; titulo?: string }
  | { tipo: 'tabela'; colunas: string[]; linhas: string[][]; titulo?: string }
  /** Regra que não se discute (inegociável). */
  | { tipo: 'regra'; numero?: number; titulo: string; texto?: string }
  /** Trecho em validação ou a definir, com quem decide. */
  | { tipo: 'alerta'; status: StatusTrecho; texto: string; quem?: string }
  /** Mensagem pronta para copiar. `{Chave}` é o que o vendedor troca. */
  | { tipo: 'script'; titulo: string; texto: string; nota?: string }
  // ── Blocos da central de ajuda (ajuda-conteudo.ts) ──
  /** Passo a passo numerado, desenhado como trilha. */
  | { tipo: 'passos'; titulo?: string; itens: string[] }
  /** Dicas de quem já usa (caixa verde). */
  | { tipo: 'dicas'; titulo?: string; itens: string[] }
  /** Erros comuns e como evitar (caixa amarela). */
  | { tipo: 'cuidados'; titulo?: string; itens: string[] }
  /** Função que ainda não existe no sistema: fica escrita como "em breve", nunca como pronta. */
  | { tipo: 'em_breve'; titulo: string; texto: string }
  /** Pergunta frequente (sanfona). */
  | { tipo: 'pergunta'; pergunta: string; resposta: string; link?: LinkFerramenta }
  /** Cartões de atalho para telas (href /comercial/...) ou seções da ajuda (href #id). */
  | { tipo: 'atalhos'; itens: Atalho[] };

/** Tela do sistema onde a regra vira ferramenta. */
export interface LinkFerramenta { rotulo: string; href: string }

/** Cartão de atalho: tela do sistema ou seção da ajuda. */
export interface Atalho { rotulo: string; href: string; texto: string; icone: string }

export interface Secao {
  id: string;
  titulo: string;
  grupo: GrupoKey;
  /** Uma linha: do que a seção trata. */
  resumo?: string;
  ferramentas?: LinkFerramenta[];
  blocos: Bloco[];
}

export type GrupoKey = 'comece' | 'lead' | 'conversa' | 'gestao' | 'areas' | 'referencia';

export const GRUPOS: { key: GrupoKey; titulo: string }[] = [
  { key: 'comece', titulo: 'Comece aqui' },
  { key: 'lead', titulo: 'Do lead ao pagamento' },
  { key: 'conversa', titulo: 'Na conversa' },
  { key: 'gestao', titulo: 'Gestão' },
  { key: 'areas', titulo: 'Áreas e processos' },
  { key: 'referencia', titulo: 'Referência' },
];

export const ROTULO_STATUS: Record<StatusTrecho, string> = {
  em_validacao: 'Em validação',
  a_definir: 'A definir',
  a_validar: 'A validar',
  a_revisar: 'A revisar',
  a_escrever: 'A escrever',
};

export const SELO = {
  versao: 'Versão 1',
  validacao: 'em validação com Jonathan Mendes',
  fonte: 'fonte: gp-operacoes',
  data: 'Escrita em 26/09/2026 com o Arthur, a partir do método do Thiago Concer e do estudo da Clint. Seções 17 a 20 acrescentadas em 03/10/2026.',
};

// Atalhos para os blocos mais usados (deixam o conteúdo legível).
const p = (texto: string): Bloco => ({ tipo: 'paragrafo', texto });
const h = (texto: string): Bloco => ({ tipo: 'subtitulo', texto });
const ul = (itens: string[], titulo?: string): Bloco => ({ tipo: 'lista', itens, titulo });
const ol = (itens: string[], titulo?: string): Bloco => ({ tipo: 'lista', itens, numerada: true, titulo });
const tab = (colunas: string[], linhas: string[][], titulo?: string): Bloco => ({ tipo: 'tabela', colunas, linhas, titulo });
const regra = (titulo: string, texto?: string, numero?: number): Bloco => ({ tipo: 'regra', titulo, texto, numero });
const aberto = (status: StatusTrecho, texto: string, quem?: string): Bloco => ({ tipo: 'alerta', status, texto, quem });
const script = (titulo: string, texto: string, nota?: string): Bloco => ({ tipo: 'script', titulo, texto, nota });

export const SECOES: Secao[] = [
  // ───────────────────────────── Comece aqui ─────────────────────────────
  {
    id: 'em-uma-frase',
    titulo: 'Em uma frase',
    grupo: 'comece',
    resumo: 'O que o playbook garante e como ele se organiza.',
    blocos: [
      p('**Todo lead tem um dono só, toda conversa está no Clint, todo negócio tem próximo passo com data, e o dia termina com o número fechado.**'),
      p('O playbook diz **o que** o comercial faz, **quem** faz e **quais regras não se discutem**. O **como**, passo a passo, mora nos processos de cada área (seção "Áreas e processos"). O preço e o que cada produto entrega moram em produtos-e-ofertas e no guia de produtos.'),
      aberto('em_validacao', 'Versão 1, de 26/09/2026. O Jonathan valida e corrige na primeira semana de operação. Onde está escrito "a definir" ou "a validar", a regra ainda não vale.', 'Jonathan Mendes'),
      h('A dor que o playbook resolve'),
      ul([
        'Não havia número de WhatsApp definido para falar com lead.',
        'Não havia controle do que sai por API.',
        'Não havia rastreabilidade fácil de onde veio cada venda.',
        'Não havia padrão de uso do Clint nem padrão de comunicação.',
        '**A dor mais cara é a distribuição:** lead sem dono claro, dois vendedores falando com a mesma pessoa, e o lead fica confuso. A sobreposição gera incerteza, objeção e desconfiança.',
      ]),
      h('O método por trás'),
      p('Thiago Concer: venda é processo, não dom. O número é consequência das habilidades em cada etapa do funil, e só melhora o que é controlado. O gestor olha o funil antes do número, cobra atividade em vez de resultado e exige o CRM em dia.'),
      ul([
        '"Você não melhora aquilo que você não controla."',
        '"Pipeline sem próximo passo não é um pipe, é só uma esperança."',
        '"Fechamento não é pressão. Fechamento é condução."',
        '"Falou o preço, fica quieto."',
        '"Nunca dê nada sem pedir algo em troca."',
      ], 'Frases do método que o time repete'),
    ],
  },
  {
    id: 'quem-e-quem',
    titulo: 'Quem é quem',
    grupo: 'comece',
    resumo: 'O time do comercial e com quem ele trabalha.',
    blocos: [
      tab(['Pessoa', 'Papel no comercial'], [
        ['Jonathan Mendes', 'Gestor da área. Define a distribuição dos leads, aprova disparos do comercial, conduz os rituais, fecha as negociações que escalam, responde pelo número do dia. É administrador do Clint'],
        ['Marcos Paulo', 'Vendedor. Dono da prospecção e da ativação de lista. Opera disparo por API dentro das regras do disparo'],
        ['Ronan', 'Vendedor. Atende e fecha os leads da fila dele. Não dispara em massa'],
      ], 'O time'),
      tab(['Pessoa', 'Para quê'], [
        ['Jéssica Ferreira (Mensageria)', 'Números de WhatsApp, templates, réguas e agenda de disparos'],
        ['João Pedro Alves (Mensageria, IA e integrações)', 'Integrações do Clint com Slack, Hotmart e relatórios'],
        ['Victor Hugo (Dados)', 'Listas, parâmetros de rastreio e links com UTM e SCK'],
        ['Isabela Teixeira (Educação)', 'O que acontece depois da compra: entrega, suporte, aluno'],
        ['Fernanda Tavares (Financeiro)', 'Pagamento, nota, reembolso'],
        ['Arthur Galvão', 'Oferta, preço e status de produto'],
      ], 'Com quem o comercial trabalha'),
      tab(['Área', 'Dono'], [
        ['Gestão comercial', 'Jonathan Mendes (a área nasce com o primeiro processo)'],
        ['Atendimento', 'Jonathan Mendes'],
        ['Prospecção', 'Marcos Paulo'],
        ['Fechamento', 'Jonathan Mendes'],
      ], 'Áreas do comercial'),
    ],
  },
  {
    id: 'o-que-vende',
    titulo: 'O que o comercial vende',
    grupo: 'comece',
    resumo: 'As duas escadas, os produtos, as regras de venda e para quem escalar.',
    ferramentas: [{ rotulo: 'Funis por produto', href: '/comercial/funil' }],
    blocos: [
      p('A casa vende para dois públicos opostos. Saber em qual escada o lead está é a primeira coisa do atendimento. **Nunca misturar as escadas.**'),
      script('A primeira pergunta de todo atendimento', 'Você quer proteger o patrimônio da própria família ou aprender a montar holding para atender clientes?', 'Separa a escada A (cliente final) da escada B (profissional).'),
      h('Escada A · serviço do escritório · cliente final com patrimônio'),
      p('Seminário da Dra. Elaine (grátis) → Sessão de Viabilidade → croqui estrutural → implantação da holding → membership.'),
      h('Escada B · infoprodutos · profissional (advogado e contador)'),
      p('CNHF e conteúdo (grátis) → Holding Total ou Clínica → Acelera Holding → Implementação Assistida (antes Holding Masters) → Aurum → Aurum+ e Diamantes.'),
      aberto('a_validar', 'Este playbook não é fonte de preço. O preço vigente de cada produto mora no arquivo do produto, em produtos-e-ofertas. Valores de edições anteriores são histórico e não se oferecem. Hoje, o único preço com decisão registrada é o da Sessão de Viabilidade: R$ 1.200 cobrados, tabela de R$ 4.800 (decisão do Arthur em 21/09/2026). Não sabe o preço, escala.', 'Arthur Galvão'),
      tab(['Produto', 'Público', 'Formato', 'Leva a'], [
        ['Seminário', 'Cliente final', 'Online, 3 noites, grátis', 'Sessão de Viabilidade'],
        ['Sessão de Viabilidade', 'Cliente final', 'Diagnóstico pago do escritório', 'Croqui, depois implantação'],
        ['CNHF', 'Profissional', 'Online, lançamento, grátis', 'Acelera Holding'],
        ['Holding Total', 'Profissional', 'Imersão de 3 dias ao vivo com o Prof. Marcio', 'Implementação Assistida'],
        ['Implementação Assistida', 'Profissional', 'Parceria (oferta do 3º dia da Imersão)', 'Aurum'],
        ['Aurum', 'Profissional avançado', 'Mentoria presencial', 'Aurum+ e Diamantes'],
      ], 'Os produtos do guia'),
      h('As seis regras inegociáveis de venda'),
      ol([
        'Garantia é sempre adicional ao art. 49 do CDC, nunca no lugar dele.',
        'Holding Total não tem gravação nem replay.',
        'Replay e treplay do Seminário são internos, não se anunciam à base.',
        'Preço vigente é o do arquivo do produto; valores de edições são histórico.',
        'Número na mesa, nunca estimativa. Não sabe, escala.',
        'Nunca misturar as duas escadas.',
      ]),
      tab(['Assunto', 'Pessoa'], [
        ['Comercial, fechamento, atendimento', 'Jonathan Mendes'],
        ['Prospecção e 1 a 1', 'Marcos Paulo'],
        ['Aurum, ETHB, entrega e pós-venda', 'Isabela Teixeira'],
        ['Preço, oferta, status de produto', 'Arthur Galvão'],
        ['Pagamento e nota', 'Fernanda Tavares'],
        ['Mensageria e links rastreáveis', 'Jéssica Ferreira'],
      ], 'Escalonamento: para quem levar o que você não sabe'),
      tab(['Lacuna', 'Dono'], [
        ['Aurum não tem arquivo de produto: entregáveis, formato, duração e pagamento não documentados', 'Arthur, com Isabela'],
        ['Implementação Assistida sem entregáveis nem prazo', 'Arthur'],
        ['Condições da garantia condicional da Implementação Assistida', 'Arthur'],
        ['Status do CNHF: histórico ou ainda tem aluno dentro', 'Arthur'],
        ['Preço do croqui e do membership (degraus 2 e 4 da escada A)', 'Arthur'],
        ['Número de encontros do Acelera (slide dizia 4, Marcio disse 3)', 'Arthur'],
        ['Política de comissionamento: versão preliminar de 08/09, não cobre os demais produtos', 'Jonathan, com Fernanda'],
      ], 'Lacunas de produto: onde o vendedor ainda fica sem resposta'),
    ],
  },
  {
    id: 'inegociaveis',
    titulo: 'Os 9 inegociáveis',
    grupo: 'comece',
    resumo: 'Valem para todo mundo, sem exceção de cargo nem de resultado.',
    ferramentas: [
      { rotulo: 'Atividades (próximo passo)', href: '/comercial/atividades' },
      { rotulo: 'Contatos (buscar dono)', href: '/comercial/contatos' },
    ],
    blocos: [
      regra('Todo lead tem um dono só.', 'O dono é definido pela distribuição, nunca por quem viu o lead primeiro.', 1),
      regra('Lead que não é seu não se toca.', 'Nem para "só tirar uma dúvida". Se o lead chamou você, transfira para o dono pelo Clint.', 2),
      regra('Se não está no Clint, não existe.', 'Conversa, ligação, proposta, objeção, venda. O que acontece fora do Clint não conta para nada.', 3),
      regra('Nenhum negócio aberto sem próxima atividade com data.', 'Sem próximo passo, o negócio é marcado como perdido, com motivo.', 4),
      regra('Quem define o próximo passo é o vendedor, não o lead.', undefined, 5),
      regra('Só se fala com lead pelos números oficiais do comercial.', 'WhatsApp pessoal não é canal da empresa.', 6),
      regra('Nenhum disparo por API sem ficha aprovada e registro no log.', undefined, 7),
      regra('Nenhuma condição fora da oferta vigente.', 'Desconto, parcela ou bônus que não está na oferta não existe. Toda condição especial tem contrapartida (pagamento à vista, decisão na hora, indicação), e só a que a oferta prevê.', 8),
      regra('Regras de marca.', 'Nunca prometer faturamento ou retorno. Garantia sempre como adicional ao direito de arrependimento do art. 49 do CDC, nunca no lugar dele. Nunca "blindagem". Nunca prometer gravação ou replay do Holding Total. "Marcio" sem acento. "Time Holding Brasil", nunca "Team".', 9),
    ],
  },

  // ───────────────────────────── Do lead ao pagamento ─────────────────────────────
  {
    id: 'funil',
    titulo: 'O funil no Clint',
    grupo: 'lead',
    resumo: 'Agrupadores, origens, etapas, critérios de passagem, alertas, campos e motivos de perda.',
    ferramentas: [
      { rotulo: 'Funil (kanban)', href: '/comercial/funil' },
      { rotulo: 'Etapas e prazos', href: '/comercial/configuracoes#funil' },
      { rotulo: 'Motivos de perda', href: '/comercial/configuracoes#motivos' },
    ],
    blocos: [
      h('Como o Clint se organiza'),
      p('No Clint, o funil se chama **origem** e o conjunto de funis de um produto se chama **agrupador**. O padrão da casa:'),
      ul([
        '**Um agrupador por produto** (Holding Total, Holding Masters, Aurum e os demais em venda).',
        'Dentro de cada agrupador, **as origens que a integração com a Hotmart cria sozinha** (carrinho abandonado, compra em aberto, cartão recusado, compra aprovada, expirada, reembolso) e **uma origem "Venda ativa"**, onde o comercial trabalha.',
      ]),
      h('Etapas da origem "Venda ativa"'),
      p('Cada etapa diz o que o vendedor tem de fazer agora, no infinitivo. Um negócio só muda de etapa quando o critério de passagem foi cumprido.'),
      tab(['Etapa', 'O que acontece aqui', 'Critério para passar', 'Alerta (atenção / crítico)'], [
        ['Fazer primeiro contato', 'Lead chegou, já com dono. Abordagem pela cadência', 'O lead respondeu', '5 min / 15 min, em horário comercial'],
        ['Qualificar', 'Conversa em andamento. Entender perfil, momento e interesse', 'Campos de qualificação preenchidos', '24 h / 48 h'],
        ['Apresentar a oferta', 'Ligação ou conversa de diagnóstico, oferta ligada à dor', 'Oferta apresentada e lead pediu condição ou link', '48 h / 72 h'],
        ['Negociar', 'Proposta e link enviados, objeções em tratamento', 'Lead escolheu a forma de pagamento', '72 h / 7 dias'],
        ['Aguardar pagamento', 'Boleto, Pix ou checkout em andamento', 'Pagamento aprovado na Hotmart', '24 h / 48 h'],
        ['Fechado', 'Ganho só com pagamento aprovado. Passagem para a Educação', '', ''],
      ]),
      regra('Ganho é pagamento aprovado, nunca "o lead disse sim".'),
      aberto('a_definir', 'Os prazos de alerta são o ponto de partida. O Jonathan ajusta depois de 30 dias de dado.', 'Jonathan Mendes'),
      h('Campos obrigatórios'),
      p('No máximo oito campos, só o que o gestor precisa saber. O Clint aceita campo obrigatório por etapa e ao marcar perdido.'),
      tab(['Campo', 'Obrigatório ao entrar em'], [
        ['Perfil profissional (advogado, contador, outro)', 'Qualificar'],
        ['Já atua com holding (sim, não, começando)', 'Qualificar'],
        ['Produto de interesse', 'Qualificar'],
        ['Origem do lead (canal e campanha)', 'Preenchido pela integração'],
        ['Objeção principal', 'Negociar'],
        ['Forma de pagamento escolhida', 'Aguardar pagamento'],
        ['Motivo de perda', 'Perdido'],
      ]),
      p('O Clint não tem campo de lista. Onde a resposta é fechada (perfil, atuação, produto), o padrão é **tag**, com os nomes definidos no arquivo do Clint.'),
      h('Motivos de perda'),
      p('Lista única para todas as origens. Motivo fora da lista não existe.'),
      ol([
        'Fora do perfil',
        'Tentativas de contato esgotadas',
        'Sem interesse',
        'Não é o momento (volta para reativação)',
        'Sem condição financeira agora (volta para reativação)',
        'Comprou outro produto da casa',
        'Contato inválido',
        'Pediu para não receber contato (vai para a lista de bloqueio)',
        'Já atendido por outro vendedor',
      ]),
      regra('O motivo 9 existe para ser medido, não para ser usado.', 'Cada ocorrência é uma falha de distribuição, e o Jonathan trata no mesmo dia.'),
    ],
  },
  {
    id: 'distribuicao',
    titulo: 'Distribuição e dono do lead',
    grupo: 'lead',
    resumo: 'Como o dono é definido na entrada, quem troca dono e o controle diário do gestor.',
    ferramentas: [
      { rotulo: 'Distribuição', href: '/comercial/configuracoes#distribuicao' },
      { rotulo: 'Contatos', href: '/comercial/contatos' },
    ],
    blocos: [
      p('A dor que esta seção resolve: lead chegando sem dono, dois vendedores falando com a mesma pessoa, lead confuso e desconfiado.'),
      h('As regras'),
      ol([
        '**Todo lead entra no Clint por integração**: Hotmart, formulário, webhook, campanha de WhatsApp ou primeira mensagem no número oficial. Nenhum lead nasce no celular de um vendedor.',
        '**O dono é definido na entrada, automaticamente, nesta ordem:** (a) o contato já tem dono em outro negócio → o negócio novo fica com o mesmo dono, quem acompanhou o lead continua com ele; (b) o contato não tem dono → a distribuição automática da origem divide entre os vendedores, no percentual que o Jonathan define; (c) exceções do Jonathan, definidas antes da campanha e escritas no projeto (por exemplo, lead de ticket alto vai para o Jonathan).',
        '**Compra aprovada entra sem dono no Clint.** O crédito da venda vai para o dono do negócio que trabalhou o lead, pela atribuição de ganho automática (exige ao menos uma atividade concluída pelo dono). Conflito de crédito, o Jonathan resolve em até 24 horas.',
        '**Troca de dono só pelo Jonathan**, com nota interna explicando o motivo. Vendedor ausente: o Jonathan redistribui a fila do dia antes das 9h.',
        '**Nenhuma conversa sem atendente.** A caixa "não atribuídos" do Clint é onde nasce a sobreposição. Ela fica zerada; conversa parada ali há mais de 15 minutos vira alerta para o Jonathan.',
        '**Disparo em massa já cria o negócio com dono.** A campanha no Clint usa a opção de criar negócio na origem e manter o atendente pelo dono. Quem responde o disparo cai direto no dono.',
        '**Antes de falar com alguém fora da fila, buscar no Clint pelo telefone.** Tem dono, não é seu.',
      ]),
      h('O controle do Jonathan'),
      tab(['Quando', 'O que confere', 'Meta'], [
        ['Todo dia, 9h', 'Filtro "sem dono" nas origens', 'Zero'],
        ['Todo dia, 9h', 'Caixa de "não atribuídos"', 'Zero'],
        ['Todo dia', 'Perdidos por "já atendido por outro vendedor"', 'Zero'],
        ['Toda semana', 'Contatos duplicados (mesmo telefone ou e-mail)', 'Mesclados'],
        ['Todo mês', 'Carga por vendedor (negócios abertos)', 'Equilibrada, dentro do limite'],
      ]),
      aberto('a_definir', 'O limite de negócios abertos por vendedor fica a definir depois de 30 dias de dado. Quem passa do limite não recebe lead novo até limpar a fila.', 'Jonathan Mendes'),
      aberto('a_definir', 'Percentual da distribuição entre Marcos Paulo e Ronan.', 'Jonathan Mendes'),
      h('O que o Clint faz e o que não faz'),
      tab(['Precisa de', 'Faz sozinho', 'Com API (plano Elite) e n8n', 'Não faz'], [
        ['Dono único na entrada', 'Distribuição por percentual e "contato com dono mantém o dono"', '', 'Não distribui lista importada, e automação não troca dono'],
        ['Etapas, campos e alerta de tempo', 'Sim', '', 'Campo de lista não existe, usa-se tag'],
        ['Conversa atribuída ao dono', 'Sim, com o número na API oficial', '', ''],
        ['Disparo em massa com relatório', 'Sim, só para administrador', '', ''],
        ['Alerta no Slack', '', 'Sim', 'Não há integração nativa'],
        ['Relatório diário automático', '', 'Sim', 'Não há relatório agendado'],
        ['Contar pelo dono do negócio', '', 'Sim, pela API', 'O painel conta pelo usuário que agiu'],
      ]),
    ],
  },
  {
    id: 'canais',
    titulo: 'Canais, números e limites de envio',
    grupo: 'lead',
    resumo: 'Por onde se fala com o lead e quanto se pode enviar por dia.',
    ferramentas: [{ rotulo: 'Conversas', href: '/comercial/conversas' }],
    blocos: [
      regra('O comercial nunca fala com lead por WhatsApp pessoal.', 'Decisão do Arthur Galvão em 03/10/2026: a proibição deixou de ser proposta e é regra. "Sempre proíba o pessoal". Enquanto o número oficial não estiver definido, a abordagem espera a definição ou sai por número da casa indicado pela Mensageria, nunca pelo pessoal.'),
      aberto('a_validar', 'O restante desta seção é proposta, a validar com a Jéssica e o Arthur: qual é o número oficial, se existe na API oficial e quem cuida.', 'Jéssica Ferreira e Arthur Galvão'),
      ul([
        '**Um número oficial do comercial** na API oficial do WhatsApp, conectado ao Clint, com setor "Comercial". Cada conversa é atribuída ao dono do lead. É o modelo que o Clint mais suporta: uma caixa, uma janela de 24 horas e um histórico por contato. Dois números para o mesmo lead geram duas conversas e voltam a criar sobreposição.',
        '**Os números da Mensageria** continuam sendo os de régua e disparo de lançamento. O comercial não usa número de disparo para conversa 1 a 1, para não queimar a reputação do número de atendimento.',
        '**Ligação** pelo VoIP do Clint, com gravação no negócio.',
        '**Nunca** o WhatsApp pessoal do vendedor.',
      ], 'Proposta'),
      h('Limites de envio'),
      tab(['Onde', 'Limite'], [
        ['Número oficial (API da Meta)', '250 conversas iniciadas por dia sem verificação do negócio; 1.000 depois'],
        ['Números fora da API', 'Regra da casa: 30 a 50 conversas novas por dia por número'],
        ['Marcação em grupo', 'Sem @all (marcação em massa denuncia automação)'],
        ['Áudio encaminhado', 'No máximo 5 por vez, espaçados'],
      ]),
      p('A casa não usa lista de transmissão. Mensagem em grupo não conta para o teto de conversas novas. Conta comercial com robô da Meta não ouve áudio: para ela, só texto.'),
      regra('Número restringido: zero envio por ele enquanto durar.', 'Nem resposta a lead novo. E nunca contornar uma restrição com outro aparelho, outro número ou reinstalação: é o que vira banimento definitivo.'),
    ],
  },
  {
    id: 'disparo-api',
    titulo: 'Disparo por API',
    grupo: 'lead',
    resumo: 'Comercial e Mensageria juntos: quem faz o quê, a ficha de 7 itens e as supressões.',
    ferramentas: [
      { rotulo: 'Fichas de disparo', href: '/comercial/disparos#fichas' },
      { rotulo: 'Agenda de disparos', href: '/comercial/disparos#agenda' },
      { rotulo: 'Templates', href: '/comercial/disparos#templates' },
    ],
    blocos: [
      p('O processo de disparo é um só e mora na Mensageria. O comercial opera dentro dele, com autonomia e com controle.'),
      tab(['', 'Jéssica (Mensageria)', 'Jonathan', 'Marcos Paulo', 'Ronan'], [
        ['Números e reputação', 'Dona', 'Segue', 'Segue', 'Segue'],
        ['Biblioteca de templates', 'Mantém e aprova os novos', 'Usa e propõe', 'Usa e propõe', 'Não'],
        ['Disparo com template aprovado', 'Sim', 'Sim', 'Sim, com ficha aprovada pelo Jonathan', 'Não'],
        ['Template novo', 'Aprova (Meta, régua, marca)', 'Escreve e propõe', 'Escreve e propõe', 'Não'],
        ['Agenda de disparos', 'Mantém', 'Consulta e marca', 'Consulta e marca', 'Consulta'],
        ['Log de disparos', 'Mantém a estrutura', 'Registra', 'Registra', 'Não'],
      ], 'Matriz de papéis'),
      h('A ficha do disparo'),
      p('Preenchida antes de todo disparo do comercial:'),
      ol([
        'Código do disparo (o mesmo no template, no log e no utm_content)',
        'Objetivo e produto',
        'Lista: filtro no Clint, quantidade, deduplicada',
        'Supressões aplicadas (abaixo)',
        'Template aprovado e número de envio',
        'Data, hora e quem opera',
        'Link rastreável (seção Rastreabilidade)',
      ]),
      p('O Marcos Paulo dispara depois do ok do Jonathan na ficha. O Jonathan dispara com a ficha registrada. **Todo disparo entra na agenda antes e no log depois.**'),
      h('Supressões obrigatórias'),
      p('Em todo disparo do comercial, fica fora:'),
      ul([
        'quem está em "Negociar" ou "Aguardar pagamento" (recebe conversa, não disparo);',
        'quem recebeu disparo da casa nas últimas 48 horas (confere na agenda);',
        'quem pediu para não receber contato;',
        'quem já comprou o produto ofertado.',
      ]),
      h('O processo da Mensageria'),
      ol([
        'Definir o segmento, deduplicado, com contagem real.',
        'Escrever a copy dentro das regras editoriais da marca.',
        'Aprovar o template antes de disparar.',
        'Conferir o limite de conversas novas por número e distribuir o volume.',
        'Disparar e acompanhar entrega.',
        'Registrar no projeto quantos receberam, quantos responderam e o resultado.',
      ]),
      p('Deu certo quando o template foi aprovado antes do envio, o volume ficou dentro do limite por número e o resultado foi registrado no projeto.'),
      aberto('a_revisar', 'O processo da Mensageria é primeira versão e está a revisar com os operadores do comercial, a ficha e as supressões.', 'Jéssica Ferreira, com o Jonathan'),
      aberto('a_validar', 'No Clint, campanha em massa é permissão de administrador. Liberar o Marcos Paulo exige grupo de permissão personalizado ou acesso de administrador, a validar na tela de permissões.', 'Jonathan Mendes'),
    ],
  },
  {
    id: 'rastreabilidade',
    titulo: 'Rastreabilidade (UTM e SCK)',
    grupo: 'lead',
    resumo: 'Todo link é rastreável e toda venda diz de onde veio e de quem foi.',
    ferramentas: [{ rotulo: 'Links por vendedor', href: '/comercial/configuracoes#links' }],
    blocos: [
      ul([
        '**Todo link que o comercial manda é rastreável**, com a convenção da casa: utm_campaign com a chave do projeto, utm_content com o código da mensagem, e SCK no padrão produto-acao-data-canal.',
        '**Cada vendedor tem os próprios links** por produto e ação, com a sigla dele no SCK. A venda que entra pela Hotmart diz de onde veio e de quem foi. Os links são criados pelo Victor Hugo.',
        '**Todo negócio tem origem preenchida.** As integrações mapeiam os campos utm_* do Clint.',
        '**Todo contato com lead sai de uma atividade do Clint.** Mensagem avulsa no chat não conta como abordagem no relatório.',
      ]),
      aberto('a_validar', 'Se a Hotmart não grava o SCK no Clint, o repasse sai pelo n8n. A validar no primeiro teste.', 'João Pedro Alves'),
      p('Por que importa: em setembro de 2026, na Imersão Holding Total, o rastreamento das duas ações do Meteórico falhou e 65 pedidos de 17 e 18/09 entraram sem SCK.'),
    ],
  },
  {
    id: 'cadencia',
    titulo: 'Cadência de contato',
    grupo: 'lead',
    resumo: 'Prazo do primeiro contato, os cinco dias de toques, depois da proposta e reativação.',
    ferramentas: [{ rotulo: 'Atividades', href: '/comercial/atividades' }],
    blocos: [
      p('A maioria das vendas perdidas por silêncio é desistência do vendedor, não do lead. Por isso a cadência é padrão e fica configurada no Clint como atividades de cada etapa.'),
      tab(['Situação', 'Prazo', 'Primeiro canal'], [
        ['Carrinho abandonado, Pix ou boleto gerado, cartão recusado', 'Até 15 min', 'Ligação, depois WhatsApp'],
        ['Lead que pediu contato ou mandou mensagem', 'Até 5 min em horário comercial', 'Responder na conversa; ligação se ele pedir'],
        ['Lead de lista ou disparo, sem pedido de contato', 'No dia', 'WhatsApp (template se a janela estiver fechada), ligação no meio da cadência'],
      ], 'Primeiro contato'),
      tab(['Dia', 'Toques'], [
        ['1', 'WhatsApp de abordagem + ligação'],
        ['2', 'Ligação + WhatsApp curto de retomada'],
        ['3', 'WhatsApp com prova (depoimento, caso)'],
        ['4', 'Ligação + WhatsApp'],
        ['5', 'Mensagem de encerramento. Negócio perdido por "tentativas esgotadas"'],
      ], 'Cadência padrão, depois do primeiro contato sem resposta'),
      p('**A mensagem de encerramento** é educada e direta: diz que este é o último contato, deixa a porta aberta e, quando houver, deixa um material de valor.'),
      p('**Depois da proposta:** até cinco tentativas, cruzando ligação e WhatsApp, com intervalo de um a dois dias. Depois, encerramento.'),
      p('**Reativação:** perdido por "não é o momento" ou "sem condição financeira agora" volta para a fila na abertura da próxima turma ou oferta do produto.'),
      regra('A mesma pessoa não recebe a régua de lançamento e a cadência do comercial no mesmo dia.', 'A agenda de disparos é onde isso se confere.'),
    ],
  },

  // ───────────────────────────── Na conversa ─────────────────────────────
  {
    id: 'conversa',
    titulo: 'A conversa',
    grupo: 'conversa',
    resumo: 'Padrão de comunicação, roteiro por etapa, qualificação, preço, objeções e fechamento.',
    ferramentas: [{ rotulo: 'Conversas', href: '/comercial/conversas' }],
    blocos: [
      h('Padrão de comunicação'),
      ul([
        '**Apresentação:** o vendedor fala em nome próprio, do time do Prof. Marcio Carvalho de Sá, e diz por que está chamando ("vi que você se inscreveu na...").',
        '**Pelo nome do lead.** Nunca "amigo", "querido".',
        '**Mensagem curta**, em blocos, uma ideia por bloco. Sem emoji e sem caixa alta, como no padrão de copy da casa. Áudio curto, só quando a conversa já está aberta.',
        '**Toda conversa termina com próximo passo e data**: "te ligo amanhã às 10h ou às 15h?".',
        '**O vocabulário da marca** vale na conversa (seção Regras de marca).',
      ]),
      aberto('a_definir', 'Horário de contato com lead. Proposta: segunda a sexta, 8h às 20h; sábado, 9h às 13h.', 'Jonathan Mendes'),
      h('Abordagem'),
      p('Pergunta antes de oferta. Deixar a intenção clara: entender o momento dele e ver se faz sentido para ele.'),
      script('Abrir com pergunta', 'O que motivou você a se inscrever?', 'Em vez de "posso ajudar?".'),
      h('Qualificação: as quatro perguntas mínimas'),
      ol([
        'Você atua como advogado, contador ou em outra área?',
        'Já trabalha com holding ou está começando?',
        'O que te fez procurar isso agora?',
        'O que acontece se isso continuar como está pelos próximos seis meses?',
      ]),
      p('Antes de apresentar, perguntar se mais alguém participa da decisão. O que o lead responde vira campo no Clint: perfil profissional, se já atua com holding e produto de interesse.'),
      script('Quem mais decide', 'Além de você, mais alguém participa dessa decisão?'),
      h('Apresentação'),
      p('Ligar cada ponto da oferta ao que o lead disse. Mostrar só o que importa para ele. Perguntar "isso faz sentido para você?" ao longo da conversa.'),
      h('Preço'),
      p('Valor antes, preço depois. Dito com firmeza, e depois silêncio. Em seguida, uma pergunta que encaminha.'),
      script('Depois do silêncio', 'Ficou alguma dúvida? Prefere no cartão ou no Pix?'),
      h('Objeções'),
      p('Nunca discutir. Devolver com pergunta e isolar.'),
      script('Isolar a objeção', 'Além disso, tem mais alguma coisa que impeça você de decidir agora?'),
      tab(['Objeção', 'Caminho'], [
        ['"Está caro"', '"Caro em relação a quê?". Voltar ao valor e ao que ele disse que precisa'],
        ['"Vou pensar"', '"Claro. O que, especificamente, você quer pensar?"'],
        ['"Depois te respondo"', 'Oferecer dois horários concretos para o retorno'],
        ['"Preciso falar com sócio ou cônjuge"', '"De 0 a 5, qual a chance real?" e "o que falta para ser 5?". Propor conversa com os dois'],
        ['"Não é o momento"', 'Pedir a dúvida específica que trava'],
        ['"Manda por e-mail"', '"Mando. Quando você me responde com certeza?"'],
      ], 'Tabela de objeções'),
      aberto('a_escrever', 'As respostas específicas de cada produto (por exemplo, "já sei fazer holding", "não tenho cliente") entram no processo de negociação, escritas pelo Jonathan com as objeções registradas no Clint.', 'Jonathan Mendes'),
      h('Fechamento'),
      p('Amarrar dor, oferta e resultado, validar, e convidar para uma escolha. Não empurrar: quem compra empurrado pede reembolso.'),
      ol([
        'Gostou?',
        'Fez sentido?',
        'Foi coerente?',
        'Atendeu ao que esperava?',
        'Vai ajudar?',
      ], 'Para o indeciso, as cinco perguntas (depois, fechar com as palavras dele)'),
    ],
  },
  {
    id: 'marca',
    titulo: 'Regras de marca na conversa',
    grupo: 'conversa',
    resumo: 'O que vale para todas as marcas e o que muda entre a base do Marcio e a da Dra. Elaine.',
    blocos: [
      p('As bases da casa têm regras editoriais opostas entre si: a mesma palavra é obrigatória numa e proibida na outra. Quem trabalha dois lançamentos ao mesmo tempo erra por inércia, não por descuido.'),
      h('Valem para todas as marcas'),
      ul([
        'Sem travessão. Vírgula, ponto ou parênteses.',
        '"Prof. Marcio" sem acento.',
        'Sem emoji, sem caixa alta gritada, sem fileira de exclamação. A comunicação da casa é sóbria.',
        'Nunca prometer gravação ou replay sem confirmação explícita do Arthur.',
        'Nunca negar o direito de arrependimento do art. 49 do CDC. A garantia é sempre adicional a ele, nunca no lugar dele. O público é de advogados e eles conferem.',
        'Negar uma palavra planta a palavra. Use o termo certo direto, sem negar o errado.',
      ]),
      h('Holding Total e base do Prof. Marcio (profissionais)'),
      ul([
        '"Holding" pode e deve: o público procura por ela.',
        'Nunca "blindagem patrimonial" nem "blindar". Usar proteger, estruturar, organizar, institucionalizar.',
        '"Time Holding Brasil", nunca "Team".',
        'Nunca prometer faturamento ou retorno.',
        'Nunca prometer gravação nem replay do Holding Total: a imersão vale pela presença, e a oferta do terceiro dia acontece ao vivo.',
      ]),
      h('Seminário da Dra. Elaine (cliente final)'),
      ul([
        '**Nada de holding na captação.** "Holding", "holding familiar", "abrir empresa" e "empresa da família" são a revelação do terceiro dia; antes disso, não se fala.',
        'Nunca "blindagem" nem "blindar".',
        'Em vez de aula, professor e aluno: encontro, live, seminário; especialista; participante, inscrito.',
        'Nunca mencionar replay ou treplay para a base, mesmo quando existem.',
        'Nunca prometer faturamento, retorno ou número de clientes. Número de patrimônio protegido ou de famílias atendidas não se usa até validação do escritório.',
      ]),
      p('Patrimônio Brasil: sem padrão editorial definido. Toda peça passa pela Ana Vieira. Aurum: política de comissão é restrita e não se replica.'),
    ],
  },
  {
    id: 'alertas',
    titulo: 'Alertas em tempo real',
    grupo: 'conversa',
    resumo: 'Cada ação do lead gera um alerta para o dono agir rápido.',
    ferramentas: [
      { rotulo: 'Integrações (Slack, n8n)', href: '/comercial/configuracoes#integracoes' },
      { rotulo: 'Atividades', href: '/comercial/atividades' },
    ],
    blocos: [
      p('**Canal:** #comercial-alertas, só com mensagens automáticas. Ninguém conversa ali. Todo alerta marca o dono.'),
      tab(['Evento', 'Alerta', 'Prazo de ação'], [
        ['Lead novo atribuído', 'Nome, produto, origem, dono, link do negócio', '5 a 15 min, conforme a cadência'],
        ['Lead mandou mensagem ou respondeu', 'Nome, dono, link da conversa', '5 min em horário comercial'],
        ['Carrinho abandonado, Pix ou boleto gerado, cartão recusado', 'Nome, produto, valor, dono', '15 min'],
        ['Venda aprovada', 'Produto, valor, vendedor', ''],
        ['Reembolso pedido', 'Produto, vendedor, com o Jonathan marcado', 'Mesmo dia'],
        ['Prazo estourado (sem primeiro contato, conversa sem resposta)', 'Dono e Jonathan marcados', 'Imediato'],
      ]),
      h('Regras do alerta'),
      ul([
        'O alerta tem dono. **Só o dono age.** Os outros não respondem o lead, e isso é o que protege contra a sobreposição.',
        'O dono confirma com uma reação no alerta quando assume.',
        'Mesma conversa gera no máximo um alerta a cada 30 minutos, para não virar ruído.',
      ]),
      p('**Como funciona:** o Clint não tem integração nativa com o Slack. Os eventos saem do Clint (webhook de etapa e de status, e o webhook de mensagem recebida da API) e da Hotmart, passam pelo n8n e chegam ao Slack. A montagem é do João Pedro.'),
      aberto('a_validar', 'Exige o plano Elite do Clint (API) e o número na API oficial. O webhook de mensagem recebida liberado na conta também está a confirmar com o suporte da Clint.', 'Jonathan Mendes e João Pedro Alves'),
    ],
  },

  // ───────────────────────────── Gestão ─────────────────────────────
  {
    id: 'fechamento-do-dia',
    titulo: 'Fechamento do dia',
    grupo: 'gestao',
    resumo: 'Todo dia útil, 19h: os números com definição exata e os alertas do dia.',
    ferramentas: [{ rotulo: 'Relatórios · fechamento', href: '/comercial/relatorios#fechamento' }],
    blocos: [
      p('Todo dia útil, às 19h, sai no #comercial o fechamento da área, como um balanço do dia. **Até as 18h45, cada vendedor deixa o Clint em dia.**'),
      tab(['Número', 'Definição exata'], [
        ['Leads abordados', 'Leads únicos que receberam um contato ativo do comercial no dia (atividade de WhatsApp ou ligação concluída, ou disparo do comercial)'],
        ['Leads que entraram em contato', 'Leads únicos que mandaram mensagem ou pediram contato no dia sem terem sido abordados antes nesse ciclo'],
        ['Leads que responderam', 'Leads abordados, em qualquer dia, que responderam no dia (entraram na etapa "Qualificar")'],
        ['Em negociação', 'Negócios abertos em "Negociar" e "Aguardar pagamento" ao fim do dia, e quantos entraram hoje'],
        ['Vendas por produto', 'Pagamentos aprovados no dia, por produto, com quantidade, valor e vendedor'],
      ], 'O que o relatório traz (cada número no total e por vendedor)'),
      ul([
        'negócios sem próxima atividade (a meta é zero);',
        'atividades atrasadas por vendedor;',
        'leads sem dono (a meta é zero);',
        'perdidos do dia, por motivo;',
        'objeções novas registradas.',
      ], 'Abaixo dos números, os alertas do dia'),
      p('Na segunda-feira, o relatório traz também a semana: conversão por etapa, tempo médio em cada etapa e perdidos por motivo.'),
      h('Como é gerado'),
      p('Pela API do Clint e pela Hotmart, montado no n8n e postado no Slack, pelo João Pedro. **Enquanto a automação não existe**, o Jonathan faz o fechamento à mão, às 19h, a partir do painel do Clint, no mesmo formato. O dia não termina sem o fechamento.'),
      regra('Pegadinha do Clint: os indicadores nativos contam pelo usuário que fez a ação, não pelo dono do negócio.', 'Por isso toda abordagem sai de uma atividade feita pelo próprio dono.'),
    ],
  },
  {
    id: 'rituais',
    titulo: 'Rituais',
    grupo: 'gestao',
    resumo: 'Daily, fechamento, 1:1, revisão do funil, treino, escuta e roda das vendas.',
    ferramentas: [{ rotulo: 'Relatórios · equipe', href: '/comercial/relatorios#equipe' }],
    blocos: [
      tab(['Ritual', 'Quando', 'Como'], [
        ['Daily', 'Todo dia útil, 9h, 15 min, presença obrigatória', 'Clint aberto na tela. Três perguntas: o que você fez ontem para avançar? O que vai fazer hoje para fechar ou alimentar o funil? Que obstáculo você tem? Problema que pede discussão sai da daily'],
        ['Fechamento do dia', 'Todo dia útil, 19h', 'Seção Fechamento do dia'],
        ['1:1', 'Semanal, 30 min por vendedor', 'Feedback em três partes (fato, impacto, ajuste esperado); as cinco oportunidades prioritárias da semana; obstáculos; compromisso com data'],
        ['Revisão do funil', 'Segunda-feira', 'Negócios parados, sem próximo passo e perdidos por motivo. Funil honesto: o que morreu é encerrado'],
        ['Treino', 'Semanal, 1 hora', 'Uma habilidade por vez, com role-play das objeções reais da semana'],
        ['Escuta', 'Semanal', 'O Jonathan ouve ou lê pelo menos uma conversa inteira de cada vendedor'],
        ['Roda das vendas', 'Mensal', 'Nota de cada vendedor em cada etapa do funil. Escolhe-se uma habilidade para desenvolver no mês'],
      ]),
      regra('Feedback de correção é sempre em particular; reconhecimento pode ser público.', 'Todo ritual termina em compromisso com data.'),
    ],
  },
  {
    id: 'indicadores',
    titulo: 'Indicadores e metas',
    grupo: 'gestao',
    resumo: 'A conta de trás para frente, os indicadores e as metas do projeto.',
    ferramentas: [
      { rotulo: 'Relatórios · funil', href: '/comercial/relatorios#funil' },
      { rotulo: 'Relatórios · equipe', href: '/comercial/relatorios#equipe' },
    ],
    blocos: [
      p('**A conta de trás para frente:** meta de receita, dividida pelo ticket, dá o número de vendas. Dividido pela conversão de cada etapa, dá quantos leads precisam passar por cada etapa e quantas abordagens por dia cada vendedor faz.'),
      tab(['Indicador', 'Para quê'], [
        ['Tempo até o primeiro contato', 'Velocidade, por vendedor'],
        ['Abordagens por dia', 'Esforço, por vendedor'],
        ['Conversão por etapa', 'Onde se perde venda'],
        ['Tempo médio em cada etapa', 'Onde o lead esfria'],
        ['Perdidos por motivo, mês a mês', 'Por que se perde venda'],
        ['Atividades concluídas contra atrasadas', 'Disciplina'],
        ['Vendas e receita por produto e por vendedor', 'Resultado'],
        ['Condição especial concedida e reembolso, por vendedor', 'Qualidade da venda'],
      ]),
      regra('Quem mais vende não é necessariamente o melhor vendedor.', 'O ranking do comercial olha volume, conversão, reembolso e o uso de condição especial.'),
      aberto('a_definir', 'As metas numéricas saem depois de 30 dias de dado limpo no Clint.', 'Jonathan Mendes'),
      tab(['Medida', 'Meta'], [
        ['Negócios sem dono', 'Zero'],
        ['Perdidos por "já atendido por outro vendedor"', 'Zero'],
        ['Tempo até o primeiro contato em carrinho, Pix, boleto e recusado', 'Até 15 min'],
        ['Disparo do comercial sem ficha', 'Zero'],
        ['Fechamento do dia', 'Todo dia útil'],
      ], 'Como saber que a estruturação deu certo (metas do projeto)'),
    ],
  },
  {
    id: 'qualidade',
    titulo: 'Padrão de qualidade',
    grupo: 'gestao',
    resumo: 'A lista de conferência: negócio em dia, venda pronta, perdido certo, disparo liberado, dia fechado.',
    blocos: [
      ul([
        'tem um dono só, definido pela distribuição;',
        'a conversa, a ligação, a proposta e a objeção estão no Clint;',
        'tem próxima atividade com data;',
        'os campos obrigatórios da etapa estão preenchidos;',
        'a origem está preenchida e todo link enviado é rastreável;',
        'só mudou de etapa com o critério de passagem cumprido.',
      ], 'Um negócio está em dia quando'),
      ul([
        'o pagamento foi aprovado na Hotmart;',
        'a condição vendida é a da oferta vigente;',
        'as regras de marca foram respeitadas na conversa;',
        'o negócio passou para a Educação.',
      ], 'Uma venda está pronta quando'),
      p('**Um negócio perdido está certo quando** o motivo é um dos nove da lista única.'),
      p('**Um disparo pode sair quando** a ficha está aprovada, as quatro supressões foram aplicadas e o disparo está na agenda. Depois de sair, entra no log.'),
      p('**O dia está fechado quando** cada vendedor deixou o Clint em dia até as 18h45 e o fechamento saiu às 19h.'),
      p('**Quem confere:** o Jonathan, pelo controle diário da distribuição, pela revisão do funil e pela escuta semanal.'),
    ],
  },
  {
    id: 'ferramentas',
    titulo: 'Ferramentas e acessos',
    grupo: 'gestao',
    resumo: 'O que o comercial usa e quem tem qual acesso.',
    ferramentas: [{ rotulo: 'Configurações do Comercial', href: '/comercial/configuracoes' }],
    blocos: [
      tab(['Ferramenta', 'Para que o comercial usa'], [
        ['Clint', 'CRM da área: origens, etapas, campos, tags, atividades, distribuição, campanha em massa e VoIP com gravação'],
        ['Número oficial do comercial (API oficial do WhatsApp)', 'Conversa 1 a 1 com o lead, conectada ao Clint (proposta, a validar)'],
        ['Hotmart', 'Checkout e pagamento. A integração cria as origens automáticas do Clint, e o pagamento aprovado marca o ganho'],
        ['n8n', 'Leva os eventos do Clint e da Hotmart ao Slack e monta o fechamento do dia'],
        ['Slack', '#comercial recebe o fechamento do dia. #comercial-alertas recebe só os alertas automáticos'],
        ['Agenda e log de disparos', 'Marcar o disparo antes e registrar depois'],
      ]),
      ul([
        'O Jonathan é administrador do Clint.',
        'Campanha em massa no Clint é permissão de administrador. A liberação para o Marcos Paulo está a validar.',
        'Os alertas e o fechamento automático exigem o plano Elite do Clint e o número na API oficial.',
        'Nenhuma credencial entra no repositório nem neste sistema.',
      ], 'Acessos'),
      aberto('a_escrever', 'O arquivo do Clint (origens, etapas, campos, tags, motivos, permissões, distribuição, números) está a escrever, na onda 1. Se o n8n e o Slack terão arquivo próprio: a definir com o Arthur Galvão.', 'Jonathan Mendes e Arthur Galvão'),
    ],
  },

  // ───────────────────────────── Áreas e processos ─────────────────────────────
  {
    id: 'area-atendimento',
    titulo: 'Atendimento',
    grupo: 'areas',
    resumo: 'Quem procura recebe resposta do dono, no prazo, com a dúvida e a objeção tratadas. Dono: Jonathan Mendes.',
    ferramentas: [
      { rotulo: 'Conversas', href: '/comercial/conversas' },
      { rotulo: 'Funil', href: '/comercial/funil' },
    ],
    blocos: [
      p('**Em uma frase.** Quem procura o comercial antes de comprar recebe resposta do dono do lead, dentro do prazo, com a dúvida e a objeção tratadas.'),
      aberto('em_validacao', 'Playbook da área versão 2, de 03/10/2026. Nada aqui foi escrito por quem executa. Quando este texto e o playbook do departamento divergirem, vale o do departamento.', 'Jonathan Mendes'),
      p('O Atendimento cuida de quem está interessado e ainda não comprou. Entra em dois momentos: **quando o lead procura a casa** (manda mensagem no número oficial ou pede contato) e **nos dias de evento ao vivo e nas janelas de carrinho aberto**, com o plantão comercial.'),
      tab(['É do Atendimento', 'Não é (de quem é)'], [
        ['Responder o interessado antes da compra: dúvida e objeção', 'Ativar lista e abordar quem não pediu contato (Prospecção)'],
        ['Plantão comercial em dia de evento e em janela de carrinho', 'Recuperar checkout, negociar e fechar (Fechamento)'],
        ['Primeiro contato com o lead que chegou (processo a escrever)', 'Entrega, suporte e aluno (Isabela Teixeira); pagamento, nota e reembolso (Fernanda Tavares); números e templates (Jéssica Ferreira); preço e oferta (Arthur Galvão)'],
      ]),
      h('O caminho de um atendimento'),
      ol([
        'O lead escreve. O dono responde na conversa em até 5 minutos, em horário comercial. Liga se o lead pedir.',
        'Se o lead chamou um vendedor que não é o dono, o vendedor transfere para o dono pelo Clint. Não responde "só para tirar uma dúvida".',
        'A primeira pergunta separa as duas escadas: "quer proteger o patrimônio da própria família ou aprender a montar holding para atender clientes?".',
        'O dono trata a dúvida e a objeção pelo roteiro da conversa.',
        'A conversa termina com próximo passo e data, registrados no Clint.',
        'O que o vendedor não sabe responder, ele escala (tabela de escalonamento). Não estima número na frente do lead.',
      ]),
      p('**Como sai:** o lead respondeu e a conversa segue para a qualificação, ou o negócio é marcado como perdido, com motivo da lista única. Conversa parada na caixa "não atribuídos" por mais de 15 minutos vira alerta para o Jonathan.'),
      h('Processo: fazer plantão comercial'),
      p('Usado nos dias de evento ao vivo e nas janelas de carrinho aberto.'),
      ol([
        '**Definir a escala** antes do dia, com nome e horário.',
        '**Ter o script e as objeções à mão**, na versão aprovada.',
        '**Usar número verificado** em toda abordagem.',
        '**Responder dentro da janela**, porque pergunta respondida depois do fechamento não vira venda.',
        '**Escalar para a coordenação** o que fugir do script, em vez de improvisar.',
        '**Registrar as objeções novas** que aparecerem.',
      ]),
      p('Deu certo quando nenhuma pergunta ficou sem resposta dentro da janela e as objeções novas entraram no registro. O plantão não começa sem escala definida e sem o script e as objeções na versão aprovada.'),
      ul([
        'o lead recebeu resposta dentro do prazo da cadência;',
        'quem respondeu foi o dono do lead;',
        'a conversa está no Clint e terminou com próximo passo e data;',
        'nenhuma condição fora da oferta vigente foi oferecida;',
        'a objeção nova foi registrada.',
      ], 'Um atendimento está pronto quando'),
      aberto('a_definir', 'Fronteira entre Atendimento, Prospecção e Fechamento por etapa do Clint; quem entra na escala do plantão; quem aprova o script do plantão e onde fica; atendimento no grupo; onde as objeções novas são registradas; indicador próprio do plantão.', 'Jonathan Mendes'),
      aberto('a_escrever', 'Processo fazer-primeiro-contato (onda 1). O processo do plantão é primeira versão, escrita por observação, e está a revisar.', 'Jonathan Mendes'),
    ],
  },
  {
    id: 'area-prospeccao',
    titulo: 'Prospecção',
    grupo: 'areas',
    resumo: 'A lista parada vira conversa: ativação, abordagem 1 a 1 e acompanhamento de MQL. Dono: Marcos Paulo.',
    ferramentas: [
      { rotulo: 'Disparos', href: '/comercial/disparos' },
      { rotulo: 'Social selling', href: '/comercial/social-selling' },
      { rotulo: 'Contatos', href: '/comercial/contatos' },
    ],
    blocos: [
      p('**Em uma frase.** A lista parada vira conversa: quem não pediu contato é abordado um a um, qualificado e entregue com dono e com registro.'),
      aberto('em_validacao', 'Playbook da área versão 2, de 03/10/2026. Os processos são primeira versão, escritos por observação e não por quem executa. O Marcos Paulo valida.', 'Marcos Paulo'),
      ul([
        '**Antes do evento.** Acompanha os MQL um a um, da pesquisa até o último dia, para aumentar o comparecimento.',
        '**Depois da janela de venda.** Aborda 1 a 1 quem passou pela janela e não comprou, com o script do Fechamento.',
        '**Na ativação de lista.** Dispara por API para uma lista, dentro das regras do disparo. Quem responde cai direto no dono.',
        '**Na reativação.** Volta a falar com quem foi perdido por "não é o momento" ou "sem condição financeira agora", na abertura da próxima turma ou oferta.',
      ], 'Os quatro momentos'),
      h('O caminho de uma ativação de lista'),
      ol([
        'O Marcos Paulo preenche a ficha do disparo: código, objetivo e produto, lista, supressões, template e número, data e hora, e link rastreável.',
        'O Jonathan aprova a ficha.',
        'O disparo entra na agenda de disparos antes de sair.',
        'O disparo sai pelo Clint, criando o negócio na origem e mantendo o atendente pelo dono.',
        'O disparo entra no log depois de sair.',
        'Quem responde cai direto no dono, que segue a cadência.',
      ]),
      p('**Prazo:** lead de lista ou de disparo, sem pedido de contato, recebe o primeiro contato no dia, por WhatsApp (template se a janela estiver fechada), com ligação no meio da cadência.'),
      ol([
        'Não dispare por API sem ficha aprovada e sem registro no log.',
        'Aplique as quatro supressões em todo disparo.',
        'Antes de falar com alguém fora da fila, busque no Clint pelo telefone.',
        'Respeite o limite de envio.',
        'Se o número for restringido, zero envio por ele enquanto durar.',
        'Nunca contorne uma restrição com outro aparelho, outro número ou reinstalação.',
        'Registre cada contato: tentou, atendeu, objeção, resultado.',
        'Respeite as regras de marca. No acompanhamento de evento, nunca mencionar replay para a base.',
      ], 'Os inegociáveis que mais pesam aqui'),

      h('Processo: abordar lead 1 a 1'),
      p('Usado depois que uma janela de venda fecha, sobre quem passou pela janela e não comprou.'),
      ol([
        '**Receber a lista** de quem esteve na janela, separada em três filas: quem clicou no link, quem só leu e quem nem abriu.',
        '**Começar pela primeira fila.** É onde está a venda.',
        '**Usar o script aprovado** do Fechamento (recuperar quem assistiu e não comprou).',
        '**Registrar cada contato**: tentou, atendeu, objeção, resultado.',
        '**Reportar ao final**: quantos tentou, quantos atenderam, quantos fecharam e quais objeções apareceram.',
      ]),
      p('As 11 regras de abordagem por WhatsApp nasceram da recuperação do Acelera Holding em 29/08/2026: 62 conversas novas em cerca de 2 horas, de um número só, com o mesmo áudio encaminhado em blocos, levaram a Meta a restringir o número. A causa provável foi a mídia, não o texto.'),
      ol([
        '**Cada responsável dispara para a própria carteira, só pelo número oficial do comercial.** Nunca pelo WhatsApp pessoal. No número oficial, valem os limites de envio.',
        '**Abrir cada conversa por link wa.me com texto pré-preenchido** (https://wa.me/<numero>?text=<mensagem>). O envio cai de cerca de 40 segundos para cerca de 5 por pessoa. É o método, não automação de interface.',
        '**Teto por número: 30 a 50 conversas novas por dia**, com **intervalo irregular de 1 a 2 minutos**, em horário comercial.',
        '**Áudio: no máximo 5 encaminhamentos por vez, espaçados.**',
        '**Converter o áudio antes de enviar.** .mpeg falha no WhatsApp Desktop; usar .mp3 ou .ogg.',
        '**Para conta comercial com robô, só texto.** Assistente virtual da Meta não ouve áudio.',
        '**Conferir quem ficou com um tique só.** Pode não ter recebido.',
        '**Limpar a fila antes de começar**: números com 12 dígitos (falta o 9 depois do DDD), números malformados e registros de teste.',
        '**Se o número for restringido, zero envio por ele enquanto durar**, nem resposta a lead novo.',
        '**Nunca contornar uma restrição com outro aparelho, outro número ou reinstalação.** É o que vira banimento definitivo.',
        '**Responder primeiro quem já respondeu.** Quem respondeu e ficou sem retorno vale mais que a lista fria inteira.',
      ], 'As 11 regras de WhatsApp'),
      p('Deu certo quando a lista inteira foi percorrida, o relatório foi enviado e as objeções foram registradas para alimentar a copy da próxima janela.'),

      h('Processo: acompanhar MQL até o evento'),
      p('**A tese:** quando o CPL sobe e o volume cai, pare de brigar pelo volume. Trabalhe o comparecimento e a conversão do que você já tem, e trate os ultra qualificados como gente, um a um.'),
      p('Usado em evento online com captação, sobre os leads que responderam à pesquisa e viraram MQL. Começa um dia depois da pesquisa e termina no último dia do evento. Existe porque, numa captação de 25 a 28 dias, quem se inscreve no começo fica 15 a 20 dias sem receber nada e esfria. **Uma mesma pessoa acompanha o lote do começo ao fim**, e é ela quem faz a recuperação depois ("você acompanhou, por que não comprou?"). Só pelo número oficial do comercial.'),
      script('Toque 1 · mensagem, um dia depois da pesquisa', 'Olá, {nome}, tudo joia? Aqui é o {seu nome}, da equipe do {especialista}. Você se inscreveu para participar do nosso evento que acontece no YouTube nos dias {datas}. Só estou passando para certificar que o senhor recebeu o presente que enviamos após sua inscrição. Chegou certinho, conseguiu ter acesso? Caso não tenha recebido, me avisa aqui que eu resolvo na hora. Ah, já aproveita e salva o meu número. Sou eu quem vai te acompanhar durante o evento.', 'O objetivo real não é o presente: é o lead salvar o número, para os toques seguintes chegarem como conversa e não como disparo.'),
      ol([
        '**Reconexão:** "não sei se lembra, mas a gente falou alguns dias atrás pelo WhatsApp".',
        '**Contexto:** o que o evento é, o que o especialista vai tratar em cada dia.',
        '**Check-in operacional:** recebeu o material? entrou no grupo? tem dificuldade de entrar no YouTube? Quem tem dificuldade recebe o passo a passo com gravação de tela.',
        '**Disclaimer de segurança:** toda comunicação sai só pelos administradores; não existe venda paralela nem abordagem durante o evento.',
        '**Compromissamento suave:** "o evento foi feito para quem vai participar ao vivo. Já separa esses dias, eu conto com a sua presença".',
      ], 'Toque 2 · ligação por WhatsApp na sexta anterior ao evento, em cinco blocos'),
      p('Se o lead for receptivo, aprofundar: "o especialista já fez {n} lives de aquecimento, posso te mandar o link?". Se não atender, mandar follow-up perguntando o melhor horário. **Desapegar depois de 24 horas** sem resposta, com elegância.'),
      script('Toque 3 · dia 1 (link no privado antes do grupo)', 'Hoje começa. O especialista vai mostrar {tema 1, tema 2, tema 3}. O link vai no grupo, mas para o senhor se antecipar, já estou te mandando por aqui. Conto com sua presença.', 'Aguardar a confirmação.'),
      script('Toque 3 · dia 2', 'Você acompanhou ontem? O que achou? Ficou com dúvida? Hoje ele vai explicar {temas}. Mando o link por aqui de novo para garantir.'),
      script('Toque 3 · dia 3', 'Hoje é o dia mais importante. Não vai ficar gravado. Vamos entregar um presente surpresa para quem estiver ao vivo. Já te mando o link antes mesmo de sair no grupo.', '"Não vai ficar gravado" casa com a regra de nunca mencionar replay para a base.'),
      ul([
        '**Reciprocidade:** "ele quer que eu participe, está me ligando. Como retribuo? Aparecendo."',
        '**Atenção individual:** quebra de padrão; o normal em evento online é receber tudo pelo grupo.',
        '**Pertencimento:** "por que esse cara está falando comigo direto, se tem 200 pessoas?"',
        '**Autoridade secundária:** "isso não é robô, é uma pessoa de verdade".',
      ], 'Por que funciona: quatro gatilhos'),
      p('**Custo operacional:** o toque 1 é a parte fácil; as ligações são a parte cara, concentradas na reta final. Referência: uma pessoa deu conta de 216 MQLs, com as ligações em dois dias. Acima disso, divida o lote entre mais pessoas antes do toque 1, porque o dono do lead não muda no meio.'),
      ul([
        'todo MQL do lote recebeu o toque 1 no dia seguinte à pesquisa;',
        'toda ligação foi tentada, e quem não atendeu recebeu follow-up e, depois de 24 horas, foi deixado em paz;',
        'o link saiu no privado antes do grupo nos três dias;',
        'o comparecimento dos MQLs acompanhados foi medido contra o dos não acompanhados, e a origem de cada Sessão de Viabilidade foi registrada.',
      ], 'Deu certo quando'),
      tab(['Ponto', 'O processo diz', 'O playbook do departamento diz (vale este)'], [
        ['Onde registrar e reportar', 'Registro e relatório no grupo da Sala de Guerra', 'Tudo no Clint'],
        ['Insistência sem resposta, no acompanhamento de MQL', 'Desapegar depois de 24 horas', 'Cadência de cinco dias'],
      ], 'Onde os processos e o playbook ainda não batem'),
      aberto('a_definir', 'Quem acompanha cada lote de MQL; ligue lead (o que é, quem faz); rotina da área fora de evento; meta de abordagens por dia; como o vendedor novo aprende a ficha de disparo; incluir no processo de MQL o script de confirmação e as três mensagens de 21/09.', 'Marcos Paulo e Jonathan Mendes'),
      aberto('a_escrever', 'Processos qualificar-lead e reativar-leads-perdidos (onda 2).', 'Marcos Paulo'),
    ],
  },
  {
    id: 'area-fechamento',
    titulo: 'Fechamento',
    grupo: 'areas',
    resumo: 'Quem chegou perto de comprar é conduzido até o pagamento aprovado. Dono: Jonathan Mendes.',
    ferramentas: [
      { rotulo: 'Estratégias', href: '/comercial/estrategias' },
      { rotulo: 'Funil', href: '/comercial/funil' },
    ],
    blocos: [
      p('**Em uma frase.** Quem chegou perto de comprar é conduzido até o pagamento aprovado, com script, fila e cadência, sem condição fora da oferta.'),
      aberto('em_validacao', 'Playbook da área versão 2, de 03/10/2026. Os três processos são primeira versão, escritos por observação e não por quem executa.', 'Jonathan Mendes'),
      ul([
        '**Evento do checkout.** Carrinho abandonado, Pix ou boleto gerado e cartão recusado entram no Clint pelas origens da integração com a Hotmart e geram alerta para o dono.',
        '**Negócio que avançou.** O lead qualificado recebeu a oferta e pediu condição ou link.',
        '**Fim de uma janela de venda.** O carrinho fecha e a área monta a fila de recuperação.',
      ], 'Como o trabalho chega: três portas'),
      ol([
        '**Qual é a oferta disponível hoje?** Preço, forma de pagamento e prazo. A mensagem não cita valor de propósito: quem cita é o vendedor, quando a pessoa pergunta. **Não inventar prazo, vaga ou lote.** Se não existe deadline real, não existe deadline na mensagem.',
        '**Cada um dispara da própria carteira, só pelo número oficial do comercial.** Nunca do WhatsApp pessoal e nunca do número do Prof. Marcio. Teto de 30 a 50 conversas novas por dia, intervalo irregular de 1 a 2 minutos, horário comercial.',
        '**Primeiro quem respondeu e ficou sem retorno.** Eles valem mais que a lista fria inteira. Ninguém abre lista nova antes de zerar essa.',
      ], 'Antes de qualquer recuperação: três decisões fechadas'),
      h('O caminho de uma recuperação de checkout'),
      ol([
        'O alerta chega. O dono liga em até 15 minutos, depois manda WhatsApp.',
        'Sem resposta, segue a cadência padrão.',
        'Recusa de cartão é tratada como problema de meio de pagamento: dados incorretos pedem link novo, saldo insuficiente pede Pix ou parcelamento maior.',
        'O lead escolhe a forma de pagamento e o negócio vai para "Aguardar pagamento".',
        'Pagamento aprovado na Hotmart: negócio fechado e passagem para a Educação.',
      ]),
      ol([
        'Não ofereça condição fora da oferta vigente.',
        'Marque ganho só com pagamento aprovado.',
        'Não deixe negócio aberto sem próxima atividade com data.',
        'Defina você o próximo passo, não o lead.',
        'Não prometa faturamento, retorno nem número de clientes. Falar do preço de mercado do serviço é fato; prometer ganho é promessa que a casa não pode cumprir.',
        'Garantia é sempre adicional ao art. 49 do CDC.',
        'Não invente prazo, vaga nem lote.',
        'Não empurre o indeciso: quem compra empurrado pede reembolso.',
        'Não toque em lead de outro vendedor. Na fila de recuperação, cada pessoa tem um responsável só.',
      ], 'Os inegociáveis que mais pesam aqui'),

      h('Processo: recuperar checkout abandonado'),
      p('Usado durante e logo após qualquer janela de venda. É a ação de maior retorno: quem chegou ao checkout decidiu e travou no último passo.'),
      ol([
        '**Puxar a lista de abandonos** do checkout.',
        '**Separar por canal disponível.** Nem todo abandono deixa telefone, e quem só deixou e-mail exige abordagem diferente.',
        '**Disparar a recuperação dentro da janela**, não depois. O valor cai a quase zero quando o carrinho fecha.',
        '**Registrar quantos voltaram** e por qual canal.',
      ]),
      aberto('a_revisar', 'Falta no processo o prazo de 15 minutos e as origens do Clint. Enquanto a revisão não sai, vale o playbook: ligação em até 15 minutos, depois WhatsApp.', 'Jonathan Mendes'),

      h('Processo: montar a fila de recuperação'),
      p('Usado quando o carrinho de um lançamento fecha (ou está para fechar). Fechamento monta e distribui; Dados entrega as bases e confere o cruzamento; cada responsável trabalha a própria carteira. Nasceu da Sala de Guerra do Acelera Holding, em 29/08/2026.'),
      ol([
        '**Juntar todas as fontes numa lista só**: interação na área de membros, base de captação, ficha de interesse, transações e histórico da Hotmart, abandono de carrinho, listas da equipe e chats das lives.',
        '**Cruzar as pessoas por e-mail OU pelos últimos 8 dígitos do telefone.** Pega quem compra com e-mail diferente do formulário (174 casos só no Acelera).',
        '**Separar os produtos nas transações**: usar só as linhas do produto do lançamento.',
        '**Reconstruir a camada de checkout a partir de transações e abandono**, sem confiar no registro da área de membros (no Acelera ela via 113 casos quando existiam 1.302 carrinhos abandonados).',
        '**Definir o universo**: os leads quentes e mornos mais todo mundo com transação, boleto ou carrinho abandonado.',
        '**Cruzar o chat só com alta confiança**: handle normalizado batendo exatamente com um nome único na base, mínimo de 12 caracteres.',
        '**Calcular o score de 0 a 100** e as faixas (abaixo).',
        '**Atribuir um responsável por pessoa.** O responsável já registrado no CRM manda; as listas da equipe completam; quem ficar sem dono é distribuído entre os escalados.',
        '**Ordenar a fila pelos sinais que mais convertem** (abaixo).',
        '**Tratar recusa de cartão como problema de meio de pagamento**, não como objeção.',
        '**Tirar da fila de ligação quem não converte** (no Acelera, profissão "outro") e limpar registros sujos.',
        '**Publicar a fila com o vocabulário de status** (abaixo). Cada mudança grava quem alterou e quando.',
        '**Aplicar a regra de prioridade**: ninguém toca em C e D antes de A e B estarem zeradas.',
      ]),
      tab(['Sinal', 'Pontos'], [
        ['Boleto em aberto', '+40'],
        ['Carrinho abandonado', '+24'],
        ['Ficha completa', '+20'],
        ['Senhas resgatadas', 'até +16'],
        ['Chat nas lives', 'até +12'],
        ['Pesquisa respondida', '+6'],
        ['Workbook', '+6'],
        ['Quer parceria', '+6'],
        ['Apostila', '+4'],
        ['Comunidade', '+4'],
        ['Advogado ou contador', '+4'],
        ['Grupo', '+3'],
      ], 'Score usado no Acelera (0 a 100)'),
      tab(['Faixa', 'Score'], [
        ['A', '60 ou mais'],
        ['B', '40 a 59'],
        ['C', '25 a 39'],
        ['D', 'Menos de 25'],
      ], 'Faixas'),
      ol([
        'Ficha completa + 6 ou mais senhas',
        'Todas as senhas, sem ficha',
        'Cartão recusado',
        'Boleto vencido e boleto em aberto',
        'Ficha completa com trilha de parceria',
        'Carrinho abandonado com algum sinal',
        'O resto, só por e-mail e disparo',
      ], 'Ordem da fila (sinais que mais convertem)'),
      p('**Status da fila:** A abordar → Tentando contato → Em conversa → Vai comprar → Ganho. Saídas: Sem resposta · Declinou · Sem interesse · Número inválido.'),
      p('Deu certo quando há uma lista única, sem duplicados, com score, faixa, responsável e status em cada pessoa; a camada de checkout reconstruída; e as faixas A e B trabalhadas antes de qualquer contato com C e D.'),

      h('Processo: recuperar quem assistiu e não comprou'),
      p('O script aprovado da abordagem, escrito pelo Arthur Galvão em 31/08/2026, usado depois de uma janela de venda de curso. Cada responsável usa na própria voz, só pelo número oficial do comercial. O Fechamento é dono do script.'),
      ul([
        '**Sem link.** Link na primeira mensagem derruba resposta e é sinal de spam. O link entra quando a pessoa pedir.',
        '**Sem oferta.** A primeira mensagem não vende, pede uma informação. Quem abre vendendo recebe "obrigado" e some.',
        '**Uma pergunta só, fácil de responder.** A pessoa tem que conseguir responder em cinco palavras, do ponto de ônibus.',
      ], 'As três regras da primeira mensagem'),
      ol([
        'Fechar as três decisões (oferta, número, quem respondeu primeiro).',
        'Montar a fila na ordem.',
        'Mandar a mensagem 1, trocando o segundo parágrafo pela variante do sinal da pessoa.',
        'Responder pelo roteiro.',
        'Dar um toque só em quem não respondeu em 24 horas, e encerrar se não houver resposta ao segundo toque.',
        'Registrar cada contato: tentou, respondeu, objeção, resultado.',
      ], 'Os passos'),
      script('Mensagem 1 · base', 'Oi {Nome}, tudo bem? Aqui é o {Vendedor}, do time do Professor Marcio.\n\nVocê acompanhou as aulas do {evento} semana passada e não chegou a entrar. Não vim insistir em venda, vim entender o que te segurou.\n\nNa pesquisa que a gente fez com a turma, quase todo mundo travou em uma de duas coisas: achar que ainda não domina a técnica pra atender um cliente de holding, ou não saber de onde viria o primeiro cliente. Foi alguma dessas duas? Ou foi outra coisa?', 'As duas portas vêm da pesquisa real: insegurança técnica aparece em quase 60% das respostas e captação de cliente é a segunda. "Não vim insistir em venda" desarma antes de a pessoa precisar se defender.'),
      p('**Variantes por sinal:** trocar só o segundo parágrafo. O resto fica igual. Os números entre parênteses são os da primeira aplicação (pós-CNHF, agosto de 2026).'),
      script('Variante · resgatou todas as senhas da Central (267)', 'Você resgatou as oito senhas da Central, até a última. Isso quase ninguém fez, foi menos de 2% da turma. Por isso estranhei não ver seu nome na lista de quem entrou.'),
      script('Variante · ficha completa e 6 senhas ou mais (233, o pool mais quente)', 'Você preencheu a ficha inteira e escreveu lá que sua maior dificuldade hoje é {dificuldade, palavra por palavra}. Foi isso que me fez te chamar.', 'Usar as palavras da pessoa, sem melhorar. Se a ficha diz "não sei como captar cliente", é isso que vai na mensagem.'),
      script('Variante · marcou trilha de parceria (662)', 'Na ficha você marcou que queria a parceria de negócio, não só a formação. Essa é justamente a parte que a aula não teve tempo de explicar direito, e é sobre ela que eu queria te ouvir cinco minutos.'),
      script('Variante · comentou no chat (382)', 'Te vi comentando no chat durante as aulas, você ficou até o fim em mais de uma. Por isso vim falar direto com você.'),
      script('Variante · entrou na comunidade e não comprou (1.472, o mais frio)', 'Você entrou na comunidade e acompanhou a semana inteira por lá. Fiquei com a impressão de que faltou pouco.'),
      h('O que responder quando a pessoa responder'),
      script('"Foi a técnica / não me sinto preparado"', 'Faz sentido, e é a resposta mais comum que a gente recebe. Deixa eu te perguntar uma coisa: você já chegou a montar uma holding do começo ao fim, ou ainda não pegou nenhum caso?', 'Ouvir primeiro. Só depois falar do método.'),
      script('"Foi cliente / não sei captar"', 'Entendi. E hoje, quando alguém te procura pra outro assunto e você percebe que a família tem patrimônio, você chega a levantar o tema de holding ou deixa passar?', 'Essa pergunta abre a conversa sozinha, porque quase todo mundo deixa passar.'),
      script('"Quanto custa?"', 'São {valor}, {condição de pagamento}. Antes de te mandar o link, me diz só uma coisa pra eu saber se faz sentido pra você agora: você pretende atender holding como área principal ou como um serviço a mais no que você já faz?', 'Responder o preço na hora, sem rodeio. Enrolar destrói a confiança que a primeira mensagem construiu.'),
      p('**"Tá caro": olhar a ficha antes de responder.** Na primeira aplicação, 45% declararam que achariam justo pagar até R$ 500, e 28% declararam valor igual ou maior que o preço cheio. Para esse segundo grupo, desconto é desperdício.'),
      script('"Tá caro" · declarou valor alto na pesquisa', 'O valor não parece ser o ponto, pelo que você mesmo respondeu na pesquisa. O que mais tá pesando?', 'Não é preço, é confiança ou momento.'),
      script('"Tá caro" · declarou valor baixo na pesquisa', 'Entendo. Só pra você ter a referência: um único trabalho de estruturação de holding no mercado costuma ser cobrado em ordem de grandeza bem acima disso. A pergunta que importa não é se cabe hoje, é se você pretende fazer disso uma frente de trabalho. Pretende?', 'Não brigar com o valor nem oferecer desconto por conta própria. Nunca prometer faturamento, retorno ou número de clientes.'),
      script('"Vou pensar"', 'Tranquilo. Te chamo {dia da semana} de manhã pra saber o que você decidiu, pode ser?', 'Marcar dia e cumprir. "Vou pensar" sem data marcada é "não" com educação.'),
      script('Sem resposta em 24 horas: um toque só', '{Nome}, só pra não deixar em aberto: prefere que eu te explique por aqui ou prefere que eu não insista? Qualquer uma das duas tá ok.', 'Se não responder ao segundo toque, encerrar. Terceira mensagem sem resposta é o que gera denúncia e derruba número.'),
      ul([
        'Contas comerciais com robô da Meta não ouvem áudio: para esses números, só texto.',
        'Áudio: no máximo 5 encaminhamentos por vez, espaçados.',
        'wa.me com texto pré-preenchido reduz de ~40s para ~5s por pessoa.',
        'Conferir quem ficou com um tique só.',
        'Não usar @all.',
        'Tirar "outra profissão" da fila de ligação: advogado converteu a 1,82%, contador a 1,56%, os demais a 0,55%.',
      ], 'Cuidados operacionais'),
      ol([
        'Quem respondeu e ficou sem retorno (41 na primeira aplicação)',
        'Ficha completa e 6 senhas ou mais (233)',
        'Todas as senhas, sem ficha (267)',
        'Ficha completa com trilha de parceria (662)',
        'Quem comentou no chat (382)',
        'Carrinho abandonado com algum sinal (1.091)',
        'O resto, só por e-mail e disparo',
      ], 'Ordem da fila do script'),
      p('Deu certo quando a fila foi percorrida na ordem, nenhuma pessoa recebeu terceira mensagem sem resposta, cada contato foi registrado e as objeções voltaram para a copy da próxima janela.'),
      tab(['Ponto', 'O processo diz', 'O playbook do departamento diz (vale este)'], [
        ['Quantos toques sem resposta', 'Um toque depois de 24 horas, e encerrar', 'Cadência de cinco dias'],
        ['Status da fila', 'A abordar, Tentando contato, Em conversa, Vai comprar, Ganho', 'Etapas da origem "Venda ativa" no Clint'],
        ['Lead sem dono', 'Rodízio ordenado por score', 'Distribuição automática por percentual'],
        ['Checkout abandonado', 'Disparar a recuperação dentro da janela', 'Ligação em até 15 minutos, depois WhatsApp'],
      ], 'Onde os processos e o playbook ainda não batem'),
      aberto('a_definir', 'Quem entra na fila de recuperação de cada lançamento; meta de taxa de recuperação; se o debriefing do comercial terá processo próprio; onde mora o script comercial de venda; o que muda depois da recuperação de checkout do Seminário de setembro de 2026.', 'Jonathan Mendes'),
      aberto('a_escrever', 'Processos seguir-cadencia-de-contato (onda 1) e conduzir-negociacao-e-fechamento (onda 2, com as objeções por produto).', 'Jonathan Mendes'),
    ],
  },
  {
    id: 'mapa-processos',
    titulo: 'Mapa de processos',
    grupo: 'areas',
    resumo: 'O que existe, o que está a revisar e o que falta escrever, em três ondas.',
    blocos: [
      p('Cada processo segue o padrão da casa (quando, quem, passos, como saber que deu certo). Quem executa escreve ou valida o seu.'),
      tab(['Processo', 'Área', 'Dono', 'Situação'], [
        ['distribuir-leads', 'Gestão', 'Jonathan', 'A escrever'],
        ['fazer-primeiro-contato', 'Atendimento', 'Jonathan', 'A escrever'],
        ['seguir-cadencia-de-contato', 'Fechamento', 'Jonathan', 'A escrever'],
        ['fechar-o-dia-comercial', 'Gestão', 'Jonathan, com o João Pedro', 'A escrever'],
        ['disparar-por-api (Mensageria)', 'Mensageria', 'Jéssica, com o Jonathan', 'A revisar: operadores do comercial, ficha, supressões'],
        ['Arquivo do Clint', 'Ferramentas', 'Jonathan', 'A escrever: origens, etapas, campos, tags, motivos, permissões, distribuição, números'],
      ], 'Onda 1 · para a área funcionar'),
      tab(['Processo', 'Área', 'Dono', 'Situação'], [
        ['conduzir-rituais-do-comercial', 'Gestão', 'Jonathan', 'A escrever'],
        ['treinar-o-time-comercial', 'Gestão', 'Jonathan', 'A escrever'],
        ['qualificar-lead', 'Prospecção', 'Marcos Paulo', 'A escrever'],
        ['conduzir-negociacao-e-fechamento', 'Fechamento', 'Jonathan', 'A escrever, com as objeções por produto'],
        ['reativar-leads-perdidos', 'Prospecção', 'Marcos Paulo', 'A escrever'],
        ['recuperar-checkout-abandonado', 'Fechamento', 'Jonathan', 'A revisar: prazo de 15 min e origens do Clint'],
        ['abordar-lead-1-a-1', 'Prospecção', 'Marcos Paulo', 'A revisar: número oficial e Clint'],
        ['acompanhar-mql-ate-o-evento', 'Prospecção', 'Marcos Paulo', 'A revisar: número oficial'],
        ['fazer-plantao-comercial', 'Atendimento', 'Jonathan', 'A revisar'],
        ['recuperar-quem-assistiu-e-nao-comprou e montar-fila-de-recuperacao', 'Fechamento', 'Jonathan', 'A revisar: dono e Clint'],
      ], 'Onda 2 · para a área melhorar'),
      tab(['Processo', 'Área', 'Dono', 'Situação'], [
        ['integrar-vendedor-novo', 'Gestão', 'Jonathan', 'A escrever'],
        ['Ascensão de aluno (Holding Total → Holding Masters → Aurum)', 'A definir', 'Jonathan e Isabela', 'Decidir dono antes de escrever'],
      ], 'Onda 3 · para a área crescer'),
      p('Contratação, remuneração e avaliação de vendedor são assunto de liderança e ficam fora do playbook.'),
    ],
  },

  // ───────────────────────────── Referência ─────────────────────────────
  {
    id: 'primeiros-30-dias',
    titulo: 'Primeiros 30 dias',
    grupo: 'referencia',
    resumo: 'O que ler, configurar e praticar no dia 1, na semana 1 e no mês 1.',
    blocos: [
      p('O processo integrar-vendedor-novo está na onda 3, a escrever. Enquanto ele não existe, vale esta ordem.'),
      ol([
        'Ler este playbook inteiro. Voltar aos inegociáveis e à distribuição dos leads até conseguir explicar os dois sem consultar.',
        'Ler o guia de produtos: as duas escadas, os produtos, as seis regras inegociáveis e a tabela de escalonamento.',
        'Ler o arquivo do produto que vai vender, em produtos-e-ofertas. O preço vigente mora lá, nunca no guia.',
        'Ler as regras de marca.',
        'Ler quem é dono de quê, para saber a quem perguntar.',
        'Receber os acessos: usuário no Clint, número oficial do comercial, canais #comercial e #comercial-alertas no Slack e links rastreáveis com a própria sigla, criados pelo Victor Hugo.',
      ], 'Dia 1 · ler e configurar'),
      ol([
        'Fazer o teste do papel: explicar a regra de dono com as próprias palavras, para o Jonathan.',
        'Participar da daily das 9h e deixar o Clint em dia até as 18h45, todo dia útil.',
        'Ler o playbook da própria área e os processos dela.',
        'Estudar a conversa e levar as objeções reais da semana para o treino.',
        'Receber a primeira fila pela distribuição.',
      ], 'Semana 1 · entrar na rotina'),
      ol([
        'Ter o 1:1 semanal com o Jonathan, com feedback em três partes e as cinco oportunidades prioritárias da semana.',
        'Ter pelo menos uma conversa inteira ouvida ou lida pelo Jonathan por semana.',
        'Participar do treino semanal e da primeira roda das vendas.',
      ], 'Mês 1 · ganhar ritmo'),
      p('Por área: quem vai **atender** lê o processo de plantão e entra na escala acompanhando alguém; quem vai **prospectar** lê os dois processos da área, o registro da restrição da Meta e o script da abordagem; quem vai **fechar** lê os três processos da área e trabalha a própria carteira numa fila de recuperação, se houver janela.'),
      aberto('a_definir', 'A lista fechada de acessos do dia 1 e quem libera cada um; se a lista dos 130 presentes do ETHB São Paulo ainda vale como primeira fila de vendedor novo; se a casa adota o acompanhamento de 30 a 45 dias (revisão a cada três dias) e a medida de ramp-up (50%, 80% e 100% do resultado esperado).', 'Jonathan Mendes'),
    ],
  },
  {
    id: 'erros-e-licoes',
    titulo: 'Erros conhecidos e lições',
    grupo: 'referencia',
    resumo: 'O que deu errado, o que mudou e o que deu certo e vale repetir.',
    blocos: [
      tab(['Quando', 'O que deu errado', 'O que mudou'], [
        ['Jun/2026, Seminário da Dra. Elaine', '84 de 115 interessados em Sessão de Viabilidade (73%) não atenderam a ligação. Só 10 compraram. O comercial respondeu por 3 de 16 vendas', 'Nenhuma mudança registrada. O que muda na operação: a definir com Jonathan Mendes'],
        ['Ago/2026, ETHB São Paulo', '130 presentes quentes que não compraram, com lead score alto, ficaram sem nenhuma ação registrada até 12/08', 'Nenhum negócio fica aberto sem próxima atividade com data'],
        ['28/08/2026, Acelera Holding', '41 leads abordados responderam e ficaram sem retorno', 'Quem já respondeu é atendido primeiro, antes de qualquer lista nova'],
        ['29/08/2026, Acelera Holding', '62 conversas novas em cerca de 2 horas, de um número só, com o mesmo áudio encaminhado. A Meta restringiu o número do Prof. Marcio', 'As 11 regras de WhatsApp e os limites de envio. Nunca disparar do número do Prof. Marcio'],
        ['29/08/2026, Acelera Holding', 'Conta comercial respondeu que o assistente virtual não ouve áudio; arquivo .mpeg falhou no WhatsApp Desktop', 'Para conta comercial com robô, só texto. Converter áudio para .mp3 ou .ogg'],
        ['Ago/2026, CNHF e Acelera Holding', 'A camada de checkout do CRM via 113 casos quando existiam 1.302 carrinhos abandonados', 'A camada de checkout é reconstruída a partir de transações e abandono; o ideal é tê-la visível durante o carrinho'],
        ['Ago/2026, CNHF e Acelera Holding', '291 recusas de cartão vieram de 31 pessoas', 'Recusa de cartão é problema de meio de pagamento, não objeção'],
        ['Ago/2026, Acelera Holding', '174 pessoas compraram com e-mail diferente do formulário', 'O cruzamento usa e-mail ou os últimos 8 dígitos do telefone'],
        ['Ago/2026, Acelera Holding', 'Quem não é advogado nem contador converteu a 0,55%, contra 1,82% do advogado e 1,56% do contador', 'Profissão "outro" sai da fila de ligação'],
        ['Set/2026, Seminário da Dra. Elaine', 'A recuperação de checkout trouxe 1 de 55. A recuperação de pesquisa não teve ação registrada', 'Sem mudança registrada. O processo de recuperação de checkout está a revisar'],
        ['Set/2026, Seminário da Dra. Elaine', 'Na recuperação de grupo por API, a efetividade caiu de 7,72% para 1,22% porque a mesma base foi tocada todo dia', 'Supressão de quem recebeu disparo nas últimas 48 horas'],
        ['Set/2026, Imersão Holding Total', 'O rastreamento das duas ações do Meteórico falhou, e 65 pedidos de 17 e 18/09 entraram sem SCK', 'Todo link é rastreável e cada vendedor tem os próprios links'],
        ['Até 26/09/2026, dia a dia', 'Lead sem dono claro e dois vendedores falando com a mesma pessoa', 'A distribuição deste playbook e o motivo de perda 9, que mede cada ocorrência'],
      ]),
      p('**O que deu certo e vale repetir.** Na semana de 21/09/2026, as ligações de ativação do Seminário saíram com script de confirmação e três mensagens padrão (não atendeu, saiu do grupo, confirmou), prontas em minutos. Levar esse material para o processo de acompanhamento de MQL ainda não foi feito.'),
    ],
  },
  {
    id: 'em-aberto',
    titulo: 'O que ainda está em aberto',
    grupo: 'referencia',
    resumo: 'Cada ponto pendente e quem decide. Enquanto não decidir, a regra não vale.',
    blocos: [
      tab(['Ponto', 'Quem decide'], [
        ['Plano do Clint: tem API (Elite)? Módulo de Automações?', 'Jonathan, com o Arthur'],
        ['Número oficial do comercial na API oficial: existe, qual é, quem cuida', 'Jéssica e Arthur'],
        ['Liberar campanha em massa para o Marcos Paulo sem dar administrador', 'Jonathan, após ver a tela de permissões'],
        ['A integração Hotmart grava UTM ou SCK no Clint?', 'João Pedro, no primeiro teste'],
        ['O webhook de mensagem recebida está liberado na conta?', 'João Pedro, com o suporte da Clint'],
        ['Horário de contato com lead', 'Jonathan'],
        ['Limite de negócios abertos por vendedor', 'Jonathan, depois de 30 dias'],
        ['Percentual da distribuição entre Marcos Paulo e Ronan', 'Jonathan'],
        ['Arquivo de ferramenta para o n8n e para o Slack', 'Arthur Galvão'],
        ['Acessos que o vendedor recebe no dia 1 e quem libera cada um', 'Jonathan Mendes'],
        ['Se a lista dos 130 presentes do ETHB São Paulo ainda vale como primeira lista de vendedor novo', 'Jonathan Mendes'],
        ['Acompanhamento de 30 a 45 dias e medição de ramp-up do vendedor novo: a casa adota?', 'Jonathan Mendes'],
        ['O que muda na operação depois de 73% das ligações não atendidas no Seminário de junho de 2026', 'Jonathan Mendes'],
        ['Fronteira entre Atendimento, Prospecção e Fechamento, por etapa do Clint', 'Jonathan Mendes'],
        ['Os pontos em que os processos das áreas e o playbook do departamento não batem', 'Jonathan Mendes, com Marcos Paulo'],
        ['Escala, script e indicador do plantão comercial', 'Jonathan Mendes'],
        ['Quem entra na fila de recuperação de cada lançamento e a meta de taxa de recuperação', 'Jonathan Mendes'],
        ['Quem acompanha cada lote de MQL, ligue lead e rotina da Prospecção fora de evento', 'Marcos Paulo'],
        ['Meta de abordagens por dia', 'Jonathan Mendes'],
      ]),
    ],
  },
  {
    id: 'glossario',
    titulo: 'Glossário',
    grupo: 'referencia',
    resumo: 'Os termos que o comercial usa no dia a dia.',
    blocos: [
      tab(['Termo', 'O que é'], [
        ['Agrupador', 'No Clint, o conjunto de funis (origens) de um produto. Um por produto'],
        ['Origem', 'No Clint, o nome do funil. A integração com a Hotmart cria as automáticas; o comercial trabalha na "Venda ativa"'],
        ['Venda ativa', 'A origem onde o comercial trabalha, com as etapas de primeiro contato a fechado'],
        ['Dono do lead', 'O único vendedor que fala com aquele lead, definido pela distribuição na entrada'],
        ['Não atribuídos', 'Caixa do Clint com conversas sem atendente. Fica zerada'],
        ['Ganho', 'Negócio fechado com pagamento aprovado na Hotmart. "O lead disse sim" não é ganho'],
        ['Próxima atividade', 'O próximo passo com data. Nenhum negócio aberto fica sem'],
        ['Cadência', 'A sequência padrão de toques (ligação e WhatsApp) depois do primeiro contato sem resposta'],
        ['Mensagem de encerramento', 'O último contato da cadência: educado, direto, deixa a porta aberta'],
        ['Reativação', 'Volta dos perdidos por momento ou por condição financeira, na próxima turma ou oferta'],
        ['MQL', 'Lead que respondeu à pesquisa de qualificação de um evento e ficou qualificado'],
        ['Ficha do disparo', 'Os 7 itens preenchidos antes de todo disparo do comercial, com o ok do Jonathan'],
        ['Supressões', 'Quem fica fora de todo disparo: em negociação, tocado nas últimas 48 h, pediu para não receber, já comprou'],
        ['Agenda e log de disparos', 'Agenda: onde o disparo é marcado antes. Log: onde é registrado depois. Estrutura da Mensageria'],
        ['Template', 'Mensagem aprovada na Meta, usada quando a janela de 24 horas está fechada'],
        ['Janela de 24 horas', 'Período em que a conversa na API oficial aceita mensagem livre, depois da última mensagem do lead'],
        ['UTM', 'Parâmetros do link: utm_campaign com a chave do projeto, utm_content com o código da mensagem'],
        ['SCK', 'Código de rastreio da Hotmart no padrão produto-acao-data-canal, com a sigla do vendedor'],
        ['Escada A', 'Serviço do escritório para o cliente final: Seminário, Sessão de Viabilidade, croqui, implantação, membership'],
        ['Escada B', 'Infoprodutos para o profissional: CNHF, Holding Total, Acelera, Implementação Assistida, Aurum'],
        ['Sessão de Viabilidade', 'Diagnóstico pago do patrimônio da família. Única porta de entrada do escritório'],
        ['Croqui estrutural', 'O desenho da estrutura de holding proposta para a família, com a calculadora do inventário'],
        ['Implementação Assistida', 'Nome atual do Holding Masters. Oferta do terceiro dia da Imersão'],
        ['Aurum', 'Mentoria presencial de alto ticket para o profissional avançado'],
        ['CNHF', 'Curso Nacional de Formação em Holding Familiar, lançamento gratuito'],
        ['ETHB', 'Encontro do Time Holding Brasil, presencial'],
        ['Fila de recuperação', 'Lista única de quem esteve perto de comprar, com score, faixa, responsável e status'],
        ['Faixas A a D', 'Prioridade pelo score: A ≥ 60, B 40 a 59, C 25 a 39, D < 25. C e D só depois de A e B zeradas'],
        ['Camada de checkout', 'Quem parou na hora de pagar, reconstruída a partir de transações e abandono'],
        ['Sala de Guerra', 'Mutirão de recuperação pós-lançamento (origem: Acelera Holding, 29/08/2026)'],
        ['wa.me', 'Link que abre a conversa no WhatsApp com o texto já digitado'],
        ['Plantão comercial', 'Escala de atendimento em dia de evento ao vivo e em janela de carrinho'],
        ['Daily', 'Reunião diária das 9h, 15 min, com o Clint aberto'],
        ['Roda das vendas', 'Nota mensal de cada vendedor em cada etapa do funil, para escolher uma habilidade a desenvolver'],
        ['Teste do papel', 'O vendedor escreve ou explica uma regra com as próprias palavras, para provar que sabe'],
        ['#comercial-alertas', 'Canal do Slack só com alertas automáticos. Só o dono age'],
        ['n8n', 'Ferramenta que leva os eventos do Clint e da Hotmart ao Slack e monta o fechamento'],
        ['Plano Elite', 'Plano do Clint com API, exigido pelos alertas e pelo fechamento automático'],
        ['Art. 49 do CDC', 'Direito de arrependimento. A garantia da casa é sempre adicional a ele'],
        ['Time Holding Brasil', 'Nome oficial da comunidade. Nunca "Team"'],
      ]),
    ],
  },
];
